version: '3.9'
services:
    app:
        working_dir: /go/app/api
        volumes:
            - .:/go/app/api
        command: bash -c "go get -d -v ./... && go build -o /tmp/api-server ./*.go && /tmp/api-server start"
        build: .
        environment:
            ENV CGO_ENABLED: 0
            API_SERVER_ADDR: ':3000'
            DATABASE_URL: postgres://local-dev@db/api?sslmode=disable
        ports:
            - '8081:3000'
        links:
            - db
    db:
        image: postgres:13-alpine
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: api
            POSTGRES_USER: local-dev
            POSTGRES_HOST_AUTH_METHOD: trust
    # docker compose --profile tools run --rm migrate up
    # docker compose --profile tools run --rm migrate down 1
    migrate: &basemigrate
        profiles: ['tools']
        image: migrate/migrate
        entrypoint: 'migrate -database postgresql://local-dev@db/api?sslmode=disable -path /tmp/migrations'
        links:
            - db
        volumes:
            - ./migrations:/tmp/migrations
    create-migration:
        <<: *basemigrate
        entrypoint: migrate create -dir /tmp/migrations -ext sql
        command: ''
volumes:
    data: